services:
  - type: web
    name: telegram-bot-antispam
    runtime: node
    branch: main
    rootDir: bot-telegram
    buildCommand: npm install
    startCommand: node bot-render-simple.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Les autres variables doivent être ajoutées manuellement dans Render:
      # BOT_TOKEN, ADMIN_ID, MONGODB_URI, RENDER_EXTERNAL_URL